logout complete

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,11 @@
+
+
+echo "Running pre-commit hook... 🍺"
+
+# Run lint-staged (which will run ESLint and Prettier on staged files)
 npm run build
+if [ $? -ne 0 ]; then
+  echo "ESLint or Prettier checks failed. ❌ "
+  exit 1
+fi
+echo "ESLint & Prettier check completed successfully. ✅"
